spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vending?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
      globally_quoted_identifiers: true
  thymeleaf:
    encoding: utf-8
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    template-resolver-order: 0
    cache: true  # 운영시 true
